### ISSUE TITLE
Today you have received another gift via PayPal :)

### ISSUE THREAD

**Issue by AlexL777** [mecha-cms/book#2]
Hi @tovic ,

I sent you another little PayPal donation today. I hope you are happy about this and motivated to continue working on Mecha CMS.

I have an extreme amount of spammers and fakers in my comments at https://mecha-cms.de Wouldn't a ReCaptcha v2 protection be better, because obviously our spam protection isn't enough.

I wasn't on the website for about a week and already had 15 spam comments. There are also manual spammers who can easily create the captcha query.

If there's anything you can do better than that. That would be my wish. 

Otherwise, much joy with the donation and I hope that it can help you something further :smile:

**Comment by tovic** [comment]
Thanks for your support. 15 spams for a week is reasonable, and they are probably created by real humans who copy and paste the spam comments and fill out the captcha field manually.

And yes, there is a bug with the form token in version 2.0.0 because its value does not change even when the page is refreshed. _Google_&rsquo;s _reCAPTCHA_ is good, but I still want to prioritize the native functionality. Need more research on this.

**Comment by tovic** [comment]
By the way, if you know who they are or at least you can guess what kind of topics that often published by the spammer, you can block them manually through the configuration file: <https://github.com/mecha-cms/extend.comment/blob/master/comment/lot/state/config.php#L25-L29>
